title = "Bilberry v4 Sandbox"
baseURL = "https://www.bilberry-sandbox.kiroule.com/"
theme = "bilberry-hugo-theme/v4"
canonifyurls = true

# Generate the robots.txt file for SEO
enableRobotsTXT = true

# Change to one of your content languages definded at the end.
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = "G-HE5BVSN9FB"

# Enable / Disable comments on the articles via Disqus.
disqusShortname = ""

[params]
  # env = "DEV"

  # baseColor = "#ff8080"

  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = ["//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css"]
  js_modules = ["//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js", "init-cookieconsent.js"]

  enableLightDarkThemeMode = true

  # Description and meta data for the search engines
  author = "Lednerb"
  description = "Bilberry Premium Theme for Hugo."
  keywords = "blog,personal,responsive,search,font awesome,pages,posts,multilingual,syntax highlighting,premium,shortcuts"

  # How many articles should be displayed at once?
  paginate = 10

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "810O6T2B5U"
  algolia_apiKey    = "1bcca9dafb3bcac6a998e554d520b239"
  algolia_indexName = "prod_bilberry_sandbox"
  # Set this option to false if you want to search within all articles in all languages at once
  algolia_currentLanguageOnly = true

  # Enable / Disable comments on the articles via commento
#  commentoJsURL = "https://commento.lednerb.de/js/commento.js"

  # Media configuration
    # let hugo automatically resize and crop your images to the correct sizes
    # NB: When enabled the image files get renamed by adding additional information,
    #     even if the image has the correct sizes.
    resizeImages = true

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "Raw HTML enabled!"

    # if you want to use libravatar or gravatar for the header image
    #avatarEmail = "code@lednerb.de"

    # set an path to the image file you want to use | overwrites avatar by email
    customImage = "bilberry-avatar-2.png"

    # define the icon you want to use for the overlay for the customImage or avatar.
    overlayIcon = "fa-home"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = true

    # always display the top navigation when scrolling
    # works only with permanentTopNav = true
    stickyNav = true

    # show a language chooser in the header
    showHeaderLanguageChooser = true

  # Content configuration
    # Enable an optional pinned page to display at the top of the index
    pinnedPost = "/article/pinned-post-test-1st-by-date/,/article/pinned-post-test-2nd-by-date/"
    # Set to true to pin only to the first page, false to all pages
    pinOnlyToFirstPage = true

    # enable automatic localization of the article's published date using Moment.js
    enableMomentJs = true

    # customize the date format | only works if momentjs is disabled | only works with English month names
    # you can customize it with the options you find here:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    dateFormat = "2006-01-02"

    # display the estimated reading time for an article
    showReadingTime = true

    # Minimum word count to display the Table of Contents
    tocMinWordCount = 100

  # Footer configuration
    showFooter = true

    # How many articles should be displayed at latest posts in the footer?
    # Set to -1 to hide the 'Latest Posts' column
    amountLatestPostsInFooter = 7

    # How many categories should be displayed in the footer section?
    # Set to -1 to hide the 'Categories' column
    amountCategoriesInFooter = 7

    # show a language chooser in the footer
    showFooterLanguageChooser = true

    # social media profile urls for the footer links
    showSocialMedia = true

    # show archive link in the footer
    showArchive = true

    # arhive grouping: "2006" by year, "2006-01" by month
    archiveDateGrouping = "2006"

    # define your links with FontAwesome 5 (only free icons are supported)
    # all icons https://fontawesome.com/icons?d=gallery&m=free
    # brand icons https://fontawesome.com/icons?d=gallery&s=brands&m=free
    socialMediaLinks = [
      { link = "https://twitter.com/TheRealLednerb", icon = "fab fa-twitter", rel="me" },
      { link = "https://github.com/Lednerb", icon = "fab fa-github" },
    ]

    # credits line configuration
    copyrightBy = "Bilberry Sandbox"
    copyrightUseCurrentYear = false  # set to true to always display the current year in the copyright
    copyrightYearOverride = "2022"
    copyrightUrl = "https://github.com/Lednerb"
    creditsText = "Powered by Bilberry Hugo Theme"
    creditsUrl = "https://github.com/Lednerb/bilberry-hugo-theme"

    # Enable / Disable Giscus comments
    giscus             = true
    giscusJsUrl        = "https://giscus.app/client.js"
    giscusRepository   = "igor-baiborodine/bilberry-hugo-theme-sandbox"
    giscusRepositoryId = "MDEwOlJlcG9zaXRvcnkyOTY2MTQ1MzY="
    giscusMapping      = "pathname"
    giscusCategory     = "General"
    giscusCategoryId   = "DIC_kwDOEa36iM4CACaU"
    giscusTheme        = "light"
    giscusReactions    = "1"
    giscusEmitMetadata = "0"
    giscusLanguage     = "en"
    giscusCrossOrigin  = "anonymous"

# customize your available languages for your multi-langual site
# or delete the [Languages] blog to use the theme with only one supported language
[Languages]
  [Languages.en]
    weight = 1
  [Languages.ru]
    weight = 1
    title = "Черничная Песочница"
    subtitle = "Необработанный HTML активирован!"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Change to 'true' if you need to render raw HTML whithin your markdown content
      unsafe = true
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"
  series   = "series"

[outputs]
  home = [ "HTML", "JSON", "RSS" ]
  page = [ "HTML" ]
