[build]
  publish = "public"
  command = "hugo"

[build.environment]
  GO_VERSION = "1.23.5"
  HUGO_VERSION = "0.141.0"

# URL: https://bilberry-sandbox.kiroule.com/
[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"
