name: Update GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Build
        run: |
          ./update-version.sh
          sed -i "s/baseURL = .*$/baseURL = \"https:\/\/igor-baiborodine.github.io\/bilberry-hugo-theme-sandbox\/\"/" config.toml
          rm -rf themes/bilberry-hugo-theme
          hugo -b "https://igor-baiborodine.github.io/bilberry-hugo-theme-sandbox/"
          > public/.nojekyll
          cat config.toml

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
