name: Update GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          sed -i "s/title = .*$/title = \"Bilberry Sandbox\"/" config.toml
          sed -i "s/baseURL = .*$/baseURL = \"https:\/\/igor-baiborodine.github.io\/bilberry-hugo-theme-sandbox\/\"/" config.toml
          sed -i "s/theme = .*$/theme = \"github.com\/Lednerb\/bilberry-hugo-theme\/v3\"/" config.toml
          hugo mod get
          version=$(grep -o 'v[0-9]\.[0-9][0-9]\.[0-9]' go.mod)
          sed -i "s/creditsText = .*$/creditsText = \"Bilberry Hugo Theme $version\"/" config.toml
          sed -i "s/creditsUrl = .*$/creditsUrl = \"https:\/\/github.com\/Lednerb\/bilberry-hugo-theme\/tree\/$version\"/" config.toml
          rm -rf themes/bilberry-hugo-theme
          hugo -b "https://igor-baiborodine.github.io/bilberry-hugo-theme-sandbox/"
          > public/.nojekyll

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
